### ISSUE TITLE
How can one use this in a diff editor?

### ISSUE THREAD

**Issue by anubra266** [x-glorious/monaco-jsx-syntax-highlight#5]
How to use monaco-jsx-syntax-highlight in monaco diff editor

**Comment by anubra266** [comment]
Figured it out for anyone who needs it


```jsx
<DiffEditor
   onMount={(editor, monaco) => {
     // ...

     const uri = monaco.getModel().uri

     const { highlighter, dispose } = monacoJsxSyntaxHighlight.highlighterBuilder({
        editor: monaco.getModifiedEditor(),
        filePath: uri?.toString() ?? uri.path,
     })
  }}
/>
```

**Comment by x-cuckoo** [comment]
> Figured it out for anyone who needs it
> 
> <DiffEditor
>    onMount={(editor, monaco) => {
>      // ...
> 
>      const uri = monaco.getModel().uri
> 
>      const { highlighter, dispose } = monacoJsxSyntaxHighlight.highlighterBuilder({
>         editor: monaco.getModifiedEditor(),
>         filePath: uri?.toString() ?? uri.path,
>      })
>   }}
> />

Bro, thanks so much, past two years, i was busy at working, thanks for replying the usage
